version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/repo

jobs:
    print-commit:
      <<: *container_config
      steps:
        - run: echo "Branch pushed!"
    print-tag:
      <<: *container_config
      steps:
        - run: echo "Tag pushed"


workflows:
    version: 2
    test-ci:
      jobs:
        - print-commit
        - print-tag:
            filters:
              branches:
                ignore:
                  - /.*/
              tags:
                only:
                  - /^staging-.*/
